apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnsa-catalog-service
  labels:
    app: cnsa-catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cnsa-catalog-service
  template:
    metadata:
      labels:
        app: cnsa-catalog-service
    spec:
      containers:
        - name: cnsa-catalog-service
          image: cnsa-catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://cnsa-postgres/cnsa_catalog
            - name: CNSA_TESTDATA_ENABLED
              value: "true"
