apiVersion: v1
kind: Service
metadata:
  name: cnsa-catalog-service
  labels:
    app: cnsa-catalog-service
spec:
  type: ClusterIP
  selector:
    app: cnsa-catalog-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001

